services:
  app:
    build: ./docker/php
    ports:
      - "28080:80"
    volumes:
      - ./app:/var/www/html
    depends_on:
      - db
    environment:
      APP_DEFAULT_LOCALE: ja_JP

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: cake
      MYSQL_USER: cake
      MYSQL_PASSWORD: cake
    ports:
      - "23306:3306"
    volumes:
      - dbdata:/var/lib/mysql

volumes:
  dbdata:
